---
name: CI/CD Pipeline
run-name: ${{ github.actor }} / ${{ github.event.head_commit.message }} 🚩

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  Validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workflows/lab1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate with Terraform
        run: terraform validate

  Checkov:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif

  Apply:
    runs-on: ubuntu-latest
    needs: [Validate, Checkov]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Terraform configs
        working-directory: workflows/lab1
        run: aws ssm get-parameter --name /devops/terraform --query Parameter.Value --output text > terraform.tfvars

      - name: Initialize Terraform
        run: terraform init

      - name: Apply with Terraform
        run: |
          echo 'Apply Terraform changes'
          echo 'Visit this link to approve the changes:'
          terraform apply | grep -A 1 'To view this run in a browser, visit:' | grep -v 'To view this run in a browser, visit:'
